server:
  port: 8082

spring:
  application:
    name: homework-service
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    url: jdbc:postgresql://localhost:5433/homework_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true

cloud:
  aws:
    region: eu-west-1
    s3:
      bucket: academix-s3
    credentials:
      access-key:
      secret-key:

jwt:
  secret: ${JWT_SECRET}

api:
  internalApiKey: ${INTERNAL_API_KEY}

services:
  homework:
    url: http://localhost:8082/api
  curriculum:
    url: http://localhost:8083/api
  user:
    url: http://localhost:8081/api

topics:
  homework-submitted: homework.submission
  homework-reviewed: homework.reviewed
  homework-reminder: homework.reminder

