spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - email
              - profile
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8081
  servlet:
    session:
      cookie:
        name: JSESSIONID
        path: /
        secure: false
        http-only: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 60000
  refreshExpirationMs: 604800000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG


