spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/oauth2/callback/google"
            scope:
              - email
              - profile
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000


