spring:
  application:
    name: academix-api-gateway
  cloud:
    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOriginPatterns:
#              - "http://localhost:5173"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - OPTIONS
#            allowedHeaders: "*"
#            allowCredentials: true
#      default-filters:
#        - RemoveRequestHeader=Cookie
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
        - id: user-service-auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - RemoveRequestHeader=Authorization
        - id: homework-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/homeworks/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: ${JWT_SECRET}