spring:
  application:
    name: curriculum-service
  datasource:
    url: jdbc:postgresql://localhost:5434/curriculum_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
        hibernate.format_sql: true
server:
  port: 8083

services:
  homework:
    url: http://localhost:8082/api
  user:
    url: http://localhost:8081/api

api:
  internalApiKey: ${INTERNAL_API_KEY}